
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import subprocess
import os

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def run_analysis():
    try:
        # Read the file path from the temporary file
        with open("/tmp/uploaded_file_path.txt", "r") as f:
            uploaded_file_path = f.read().strip()
        print(f"File path for analysis: {uploaded_file_path}")  # Debugging
        
        # Run the analysis
        result = subprocess.run(["python3", "../image_analyzer.py", uploaded_file_path], capture_output=True, text=True)
        print(result.stdout)  # Debugging: Print the analysis output to the console
        
        # Save the results to a file
        with open("image_result.txt", "w") as f:
            f.write(result.stdout)
        
        # Navigate to the results screen
        window.destroy()
        os.system("python3 Imageresults.py")
    except FileNotFoundError:
        print("Error: Temporary file with uploaded path not found.")

window = Tk()

window.geometry("1619x924")
window.configure(bg = "#000212")


canvas = Canvas(
    window,
    bg = "#000212",
    height = 924,
    width = 1619,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    809.0,
    462.421142578125,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    324.245361328125,
    79.752685546875,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    809.0,
    481.6263122558594,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=run_analysis,  # Run analysis and navigate to results
    relief="flat"
)
button_1.place(
    x=55.0001220703125,
    y=769.4419555664062,
    width=1508.9998779296875,
    height=64.68696594238281
)

canvas.create_text(
    55.182861328125,
    148.7994384765625,
    anchor="nw",
    text="Image Uploaded!",
    fill="#FFFFFF",
    font=("Inter", 33 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    815.0,
    462.0,
    image=image_image_4
)
window.resizable(True, True)
window.mainloop()
