
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os

from pathlib import Path
from subprocess import Popen

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")

# Define navigation actions
def select_image():
    window.destroy()  # Close current window
    os.system("python3 Uploadimage.py")  # Navigate to Uploadimage

def select_document():
    window.destroy()  # Close current window
    os.system("python3 Uploaddocument.py")  # Navigate to Uploaddocument

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1619x924")
window.configure(bg = "#000212")


canvas = Canvas(
    window,
    bg = "#000212",
    height = 924,
    width = 1619,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    809.0,
    462.421142578125,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    324.245361328125,
    79.752685546875,
    image=image_image_2
)

canvas.create_text(
    55.182861328125,
    148.7994384765625,
    anchor="nw",
    text="Welcome to SecureDoc Scanner! Select Image or Document to Scan for Threats.",
    fill="#FFFFFF",
    font=("Inter", 33 * -1)
)

canvas.create_text(
    55.245361328125,
    205.86383056640625,
    anchor="nw",
    text="SecureDoc Scanner offers malware detection for images and documents, helping you identify and prevent threats. Detect hidden risks and keep your data secure with this easy-to-use tool.",
    fill="#FFFFFF",
    font=("Inter", 16 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    427.245361328125,
    514.8514404296875,
    image=image_image_3
)

canvas.create_text(
    256.7939453125,
    307.1055908203125,
    anchor="nw",
    text="Scan an Image for Malicious Content",
    fill="#FFFFFF",
    font=("Inter SemiBold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=select_image,  # Navigate to Uploadimage.py
    relief="flat"
)
button_1.place(
    x=56.0,
    y=770.18212890625,
    width=744.0,
    height=54.80989456176758
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1192.0,
    514.8514404296875,
    image=image_image_4
)

canvas.create_text(
    996.3773193359375,
    307.1055908203125,
    anchor="nw",
    text="Scan an Document for Malicious Content",
    fill="#FFFFFF",
    font=("Inter SemiBold", 20 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=select_document,  # Navigate to Uploaddocument.py
    relief="flat"
)
button_2.place(
    x=820.0,
    y=770.18212890625,
    width=744.0,
    height=54.80989456176758
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    408.56884765625,
    599.0963134765625,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1156.143310546875,
    577.9058227539062,
    image=image_image_6
)
window.resizable(True, True)
window.mainloop()
